### ISSUE TITLE
What's the purpose of disabling IPv6?

### ISSUE THREAD

**Issue by lavacano201014** [CHEF-KOCH/regtweaks#11]
Because from what I know of IPv6 and all the problems IPv4 is either dealing with or about to deal with, disabling IPv6 seems like a very bad idea.

If there's a nasty bug in MS' v6 stack, sure, but otherwise I'm confused

**Comment by CHEF-KOCH** [comment]
My troughs on this why you should disable IPv6:
* [Fixes boot delays](http://www.thewindowsclub.com/disable-ipv6-5-second-boot-delay)
* [IPv6 addresses by default incorporate hardware MAC addresses, and that's a very bad thing for privacy in two ways. Few if any VPN services route IPv6, and so IPv6 traffic on your physical NIC may leak information about your online activity. And even if VPNs route IPv6, it's leaking your hardware MAC address.](http://superuser.com/questions/243669/how-to-avoid-exposing-my-mac-address-when-using-ipv6)
* [Defcon recommed it](http://www.defcon.org/images/defcon-...ndqvist-WP.pdf)
* Not all ISP's supporting IPv6
* [Possible VPN leaks](https://www.expressvpn.com/blog/disable-ipv6-for-better-vpn-protection/)

Of course there are also some benefits using IPv6 but at the end you need a lot of other tweaks to bringing IPv6 on the right track so we should force them to fix the protocol and the issue instead of supporting it. otherwise they never change something and at the end there is no benefit over IPv6 then.

**Comment by lavacano201014** [comment]
>Fixes boot delays

The article you linked describes a boot delay when IPv6 is disabled incorrectly. The part I care about more is, if you're getting a boot delay with IPv6, that's a bug in your operating system, not the protocol itself. Blame Microsoft for that one.

>VPN related

That also sounds like a problem with VPN providers, not with the protocol itself. That said, I haven't looked through my OpenVPN configs to see if I can route IPv6 through my self hosted one, because of the below point

>Not all ISPs supporting IPv6

Normally irrelevant, since it's good to have and not need, but considering the boot delay point above, fair.

>Defcon recommend it

At time of writing this comment, the link is busted (goes to www.defcon.org/images/defcon- **...** ndqvist-WP.pdf - copy/paste the wrong thing?).

--

I'm going to close this issue now, because technically, my question is answered (and I actually see the justification, even if we disagree on which parts actually need fixed). This should not be interpreted as an attempt to halt discussion, merely a "good housekeeping" kind of move.

**Comment by CHEF-KOCH** [comment]
The boot delay fixes both sides, even disabling IPv4 cause the loopback interfaces are still running. This can't be fixed by registry you need to use netsh command to ensure that there is no loopback is running otherwise this causes the issue, well the link was only an example. 

VPN related issue are protocol related issue, never VPN services related issue cause the VPN provider only offer encryption over specific protocols and 'tweaking' this by their provided service configuration which establish the connection. This does not fix the protocol issue by itself. For example IPSec is still secure while everyone wrongly writes NSA 'broke' that, which is totally untrue, they used and exploit and this is not fixed in later protocol versions and stronger configurations. So the ISP is not the issue cause an exploit can be applied to every software/protocol (if such thing exist). So how should they know what NSA could exploit when nothing was leaked? Same goes to IPv6 because it leaks a lot of more information. 

> Normally irrelevant, since it's good to have and not need, but considering the boot delay point above, fair.

This is totally relevant, cause why 'using' IPv6 when your ISP not native supports that? The chance is high when you use protocols/interfaces you not use that this can be abused and you lower such attack by disabling it. 


> At time of writing this comment, the link is busted (goes to www.defcon.org/images/defcon- ... ndqvist-WP.pdf - copy/paste the wrong thing?).

Yeah sorry about that, I fixed the link cause I realized I copied the url wrong.

**Comment by Gitoffthelawn** [comment]
Good discussion.

@CHEF-KOCH On your second bullet point, that is fixed in Windows since XP days, no?

Also, just FYI, in the last sentence of your first post in this issue, I think you meant "IPv4", not "IPv6".

**Comment by CHEF-KOCH** [comment]
Sorry my mobile GitHub app is trolling me today. :trollface:

**Comment by Gitoffthelawn** [comment]
LOL.  Looks good now! :)

BTW, do you agree that the second bullet point is fixed in Windows?  Or am I not understanding something?

**Comment by CHEF-KOCH** [comment]
I'm unsure because I'm not 100% sure how to test and verify if that is fully fixed or not.
