### ISSUE TITLE
.zip package contains wrongly encoded files

### ISSUE THREAD

**Issue by freesoft0000** [CHEF-KOCH/regtweaks#20]
The registry file encoding should be Unicode or ANSI.
But the file encoding you uploaded is utf-8. 
And the line break is incorrect.

**Comment by CHEF-KOCH** [comment]
I'm surprised someone finally found out.

**Comment by freesoft0000** [comment]
![快照18](https://user-images.githubusercontent.com/30435921/57189271-25d74b00-6f3f-11e9-8905-66cb44224dac.png)
![Uploading 快照19.png…]()

**Comment by freesoft0000** [comment]
![快照19](https://user-images.githubusercontent.com/30435921/57189276-338cd080-6f3f-11e9-942f-3495423fe383.png)

**Comment by CHEF-KOCH** [comment]
Not reproducible on my end, it works for me without any problem. 

![vfddvv](https://user-images.githubusercontent.com/727123/57189341-f52aed80-6f0d-11e9-8209-7cb5d15eed2b.png)

**Comment by freesoft0000** [comment]
My running Environment Simplified Chinese operating system
Using UTF-16 encoding is not a good note.
File Open garbled code

**Comment by freesoft0000** [comment]
Open a file to use notepad++

**Comment by CHEF-KOCH** [comment]
> Using UTF-16 encoding is not a good note.

Yes it is, for [registry .reg files](https://docs.microsoft.com/en-us/windows/desktop/sysinfo/registry-value-types) it's the default. UTF-8 (like it was before, [also works](https://gist.github.com/SalviaSage/8eba542dc27eea3379a1f7dad3f729a0)) but I converted it to prevent importing related issues and to have all files the same encoded.

Your issue is not reproducible (for me) no matter which OS or language I use, I tried Russian, Korean and traditional Chinese Windows 7. I try simplified Chinese when I have more time.

You could test the PowerShell script to convert the files (save it as _whatevceryouwant.ps1_ place it into the same folder with the files you want to convert and start the script. You can change the `-Encoding` option to whatever you want, see [here what powershell supports](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6).
```Powershell
Get-ChildItem *.ps1 -Recurse | ForEach-Object {
    $content = Get-Content -Path $_
    Set-Content -Path $_.Fullname -Value $content -Encoding Unicode -PassThru -Force
}
```

In case that still fails then this means that something is wrong with your Notepad++ configuration. The project mentions several workarounds over [here](http://docs.notepad-plus-plus.org/index.php/Encodings_And_Character_Display). You could try to use one of the advises.

**Comment by freesoft0000** [comment]
![111](https://user-images.githubusercontent.com/30435921/57207700-d6a61e80-7001-11e9-97d7-e9db401048be.png)
![110](https://user-images.githubusercontent.com/30435921/57207705-db6ad280-7001-11e9-8903-3600eb0bf42d.png)
![112](https://user-images.githubusercontent.com/30435921/57207706-db6ad280-7001-11e9-9264-16119ddd9003.png)

**Comment by CHEF-KOCH** [comment]
![feffeef](https://user-images.githubusercontent.com/727123/57256827-fec06c80-7057-11e9-8ac8-ca910e216293.png)


If there are display problems with Chinese characters then please switch to another Editor which displays them correctly, like Visual Studio Core or use the mentioned converter Powershell script. Even VS Code still has some [issues with it](https://github.com/Microsoft/vscode/issues/45730) but I provided a workaround to avoid this from happening.

<details>
 <summary>Long story</summary>
<p>
I spend a lot of time doing some research on this and I even talked with GitHub itself about the issue and it's not my project or the files. What the problems, is that some Editors incorrectly read the header which results in garbled code. I already tried to change everything to BOM and I even tried it without BOM but it made things worse because Notepad++ and EMEditor looking for BOM in such files (automatically). However, the problem is that I can't use UTF-8 with BOM because it results for some users into importing problems. So I use MS suggestion to go with their defaults for registry .reg files. 

My apologies if some people are unhappy now, but this is more complicated than it sounds because there are lot of variables to consider, like which Editor you use, which language you use under Windows, which settings GitHub uses/prefer and which settings git itself uses across different platforms. I believe I found the correct way to solve this. 
</p>
</details>

**Comment by freesoft0000** [comment]
You have an error in making the encoding conversion. You can export a registry file using the Regedit program that comes with the system to see the encoding format
![110](https://user-images.githubusercontent.com/30435921/57275465-3a4b4d00-70d1-11e9-9c71-bad5b8c7cba1.png)
![111](https://user-images.githubusercontent.com/30435921/57275467-3ae3e380-70d1-11e9-9522-b4f1ae0200c2.png)
![112](https://user-images.githubusercontent.com/30435921/57275468-3ae3e380-70d1-11e9-8bdc-2c20faf75bc0.png)
![113](https://user-images.githubusercontent.com/30435921/57275470-3ae3e380-70d1-11e9-88e0-3c08d1a800a4.png)

**Comment by CHEF-KOCH** [comment]
CRLF is correct the other files are automatically converted by GitHub. I'm not sure how long it takes.

**Comment by freesoft0000** [comment]
Here's a right example.
https://github.com/iwanczuk/windows-regs

**Comment by CHEF-KOCH** [comment]
It's not helpful what you do here, especially if I said I had to remove BOM headers, the next thing you do is showing me a picture without any information that your files including BOM headers. 

For registry files without BOM you have to force your editor to properbly handle .reg files (as I already explained s [this post](https://github.com/CHEF-KOCH/regtweaks/issues/20#issuecomment-489454510)). This 100% works on my end and I double-checked it.
