### ISSUE TITLE
[Not with me] Windows 7 and Server 2008 Get 0patch Security Fixes After EoS

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/regtweaks#23]
### Info
* Microsoft is ending the official support for Windows 7 and Server 2008 early next year (January 14, 2020) and will also stop delivery of security patches through the normal channel, aka WUS (Windows Update Server). 
* 0Patch (ACROS Security) wants to provide "micropatches"., this basically means they provide unofficial security patches. These are not KBs and they are tiny. We are talking about [byte size micropatches](https://0patch.zendesk.com/hc/en-us/articles/360018110474) (that's why they called "micro").
* [Official Blog Post](https://blog.0patch.com/2019/09/keeping-windows-7-and-windows-server.html).
* Micropatches will normally be available to paying customers (Pro - $25/agent/year - and Enterprise license holders) according to their website, however they say there will be support for non paid customers too (without going into further details how that looks like).

### MS Extended security updates
* Extended Security Update (ESU) is around $350 for each computer.
* The Windows Virtual Desktop program, which enables organizations to continue using the operating system with free extended security updates until 2023, it's unclear what happens after 2023.
* [Security support for Entp. users e.g. Gov. ends 2020](https://blogs.microsoft.com/on-the-issues/2019/09/20/extending-free-windows-7-security-updates-to-voting-systems/).

### My point of view
**I'll drop Windows 7 support the moment the official support ended**. I do not believe the nonsense what the [0Patch platform provides](https://www.0patch.com/). For me this is a shady trick to make some money, instead of providing questionable micropatches how about working together with MS to solve the issue in e.g. Windows 8.1/10? 

I don't understand the motivation behind this, why not upgrade ([the free upgrade trick still works](https://www.howtogeek.com/272201/all-the-ways-you-can-still-get-windows-10-for-free/))  from e.g. 7 to 10 for free? We had this with XP and people refused to make the switch, and I saw CVEs over CVEs right after that, hackers abused it e.g. with Ransomeware. Only 10 had an _effective_ protection (aka pre-installed Windows Defender).

I agree that a switch can be problematic (see Vista) but now we got already 8 (dead) and 8.1 + 10. If there are privacy concerns use the LTSC versions or ensure you use the latest stable builds which allowing you to "shutdown" background apps and restrict access to your mic etc even on Pro versions.

Fooling people with questionable security promises in order to make some quick cash is definitely not what I suggest my followers/readers. Instead, I urge you to update to the latest versions (always) without any compromise.

**Comment by blackcrack** [comment]
Hi Chefkoch,

https://github.com/CHEF-KOCH/NSABlocklist/issues/53

if there exist a WinNT Group, why not support a build up of WinNT out of the Internetcommunity to take that Toy and Moneymaker out of the Hand from Microsoft.

The always build up a new Windows,  pushing support for the current version and stopping that WinNT version.. and stop a support for this "Windowsversion" because to sell Support to the factory's and let open the backdoors or possibility's for US facilities what it is wrote in the US law's..
the whole things behind that make the MS-WinNT not more really secure ..

The Reactos.org community will stay.. and stay behind the whole update like the way want go..
and dropping support, why.. it is only a making money thing and politic of it.. or behind of it..

that's not only why..  build up Reactos.. and not only because the dropping of Support like now and in the past XP, it's much more  .. ask friends to help with, then can you say.. "not with me"
because we have Reactos .. out of the Internet community .. under GPL2 for free and as free/open source software up to the NT-Kernel in any corner ..

best regards
Blacky

best regards
Blacky
