### ISSUE TITLE
Do you have a script to allow dragging fullscreen programs like firefox to the other monitor all the time?

### ISSUE THREAD

**Issue by seiterseiter** [CHEF-KOCH/regtweaks#3]

**Comment by CHEF-KOCH** [comment]
No, script based is not really useful because you might want to start several different apps after time x. But there are already tools available to [do this](https://stackoverflow.com/questions/26076363/creating-a-script-in-ahk-that-will-move-the-window-over-put-it-in-fullscreen-a) and a bit [source code](https://github.com/Grumbel/fullscreen-tools).

Take a loot at:
* [Execute a program in a second monitor](http://www.codeproject.com/Tips/264893/Execute-a-program-in-second-monitor)
* [Multi Monitors](http://www.nirsoft.net/utils/multi_monitor_tool.html)
* [DisplayFusion](http://www.binaryfortress.com/displayfusion/)
* [Synergy](http://synergy2.sourceforge.net/)
* [UltraMon](http://www.realtimesoft.com/ultramon/)
* [MultiMon](http://www.mediachance.com/free/multimon.htm)

**Comment by mikhoul** [comment]
I use <ins>Actual Windows Manager</ins> to do this: http://www.actualtools.com/windowmanager/ it work very well. :smiley:
